spring:
  application:
    name: game-service
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 9001

app:
  persistence: memory
  logic-service:
    enabled: false
    base-url: http://localhost:9002
